#!/bin/bash

raco test -j 10 /Users/badkins/Desktop/RacketConTalk/source/racket-joy/*.rkt /Users/badkins/Desktop/RacketConTalk/source/racket-joy/axio/*.rkt /Users/badkins/Desktop/RacketConTalk/source/racket-joy/controllers/*.rkt /Users/badkins/Desktop/RacketConTalk/source/racket-joy/models/*.rkt
